/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as RepositoryRouteImport } from './routes/repository'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/protocols': typeof ProtocolsRoute
  '/repository': typeof RepositoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/protocols': typeof ProtocolsRoute
  '/repository': typeof RepositoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/protocols': typeof ProtocolsRoute
  '/repository': typeof RepositoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents' | '/protocols' | '/repository'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/protocols' | '/repository'
  id: '__root__' | '/' | '/agents' | '/protocols' | '/repository'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ProtocolsRoute: typeof ProtocolsRoute
  RepositoryRoute: typeof RepositoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ProtocolsRoute: ProtocolsRoute,
  RepositoryRoute: RepositoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
